#!/bin/bash

TIMEOUT=2
LOG=devmode.log

function print_help() {
	echo "usage: devmode file
		
Watches a dart script every $TIMEOUT sec for changes and recompiles it to Javascript using the dart2js compiler at the moment the script changes.

arguments:
file    The targeted dart script for recompiling" | fold -sw 80
}

function watch_changes() {
	FILE=$1
	TARGET="$(target_name_from_file $FILE)"

	if [ ! -f $FILE ]; then
		echo "Cannot find file '$FILE'. Exiting..."
		exit
	fi

	echo "Watching for changes in '$FILE' every $TIMEOUT sec."
	echo "Redirecting dart2js logs to $LOG"
	while true; do
		if [ ! -f $LOG -o $FILE -nt $LOG ]; then
			compile $FILE $TARGET
		fi
		sleep $TIMEOUT
	done
}

function target_name_from_file() {
	echo $1.js
}	

function compile() {
	FILE=$1
	TARGET=$2
	echo -n  "[$(date)] Compiling... " | tee -a $LOG
	OUTPUT=$(dart2js $FILE -o $TARGET 2>&1)

	if [ -z "$OUTPUT" ]; then
		echo "done" | tee -a $LOG
	else
		echo "failure" | tee -a $LOG
		echo "Error during compilation:" | tee -a $LOG
		echo $OUTPUT | tee -a $LOG
	fi
}

function assert_path_for_dart2js() {
	PATH_TO_DART2JS=$(which dart2js)
	if [ ! -x "$PATH_TO_DART2JS" ]; then
		echo "Please add the dart2js compiler to your path. Exiting..."	
		exit 1
	fi
}

assert_path_for_dart2js

if [ $# -eq 1 ]; then
	watch_changes $1
else
	print_help
fi
